[package]
name = "tokrio"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
rio = "0.9"
socket2 = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
