[package]
name = "ordered-map"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
atone = "0.3"
indexmap = "1"
linked-hash-map = "0.5"
twox-hash = "1"
