[package]
name = "channel-perf"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["time", "sync", "rt", "rt-multi-thread"] }
futures = "0.3"
flume = "0.10"
