[package]
name = "mempool"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
#refpool = "0.4"
object-pool = "0.5"
threadpool = "1"
lazy_static = "1"
