[package]
name = "microbenchmarks"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
regex = "1"
rustls = "0.19"
futures = "0.3"
oneshot = "0.1"
num_cpus = "1"
futures-timer = "3"
rand_core = "0.6"
capnp = "0.14"
konst = "0.2"
nolock = "0.3"
chrono = "0.4"

[dependencies.febft]
git = "https://github.com/febft/febft"
rev = "ed5eef75ec4b158ea248cc0dab8a760d58192362"
default-features = false
features = [
    "expose_impl",
    "async_runtime_async_std",
    "threadpool_crossbeam",
    "socket_async_std_tcp",
    "channel_futures_mpsc",
    "crypto_signature_ring_ed25519",
    "crypto_hash_blake3_blake3"
]

[build-dependencies.capnpc]
version = "0.14"
