[package]
name = "consensus"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
bincode = "1.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
