[package]
name = "signatures"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[dependencies]
#hacl-star = "0.1.0"
hacl-star-gcc = { git = "https://github.com/ditto-bft/rust-hacl-star" }
sodiumoxide = "0.2.6"
